<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b7cd949d-8b58-4ce0-8a7b-4d815750067e</testSuiteGuid>
   <testCaseLink>
      <guid>acb35dae-2074-4ade-9d89-9422bc4cbccc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Login/Positive/TC1_Positive_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f33d614-2f4e-4adc-9bbc-4839e3ef067a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c78a1b-af55-4fe7-9769-6471c664d6c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12a1dec7-c21d-4b4b-a897-16ce7e5255bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2add3dda-10df-484c-9699-d8667c0826f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Login/Positive/TC2_Positive_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cc356b8f-3ea5-4908-8a40-c3fcb3bbe8f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Login/Positive/TC3_Positive_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c0a31c3a-56d8-4cf4-874b-a39bdb680b34</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Login/Negative/TC1_Negative_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f33d614-2f4e-4adc-9bbc-4839e3ef067a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c78a1b-af55-4fe7-9769-6471c664d6c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a97c45b-148d-4ccc-b646-9fe3dbbbd069</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Login/Negative/TC2_Negative_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f33d614-2f4e-4adc-9bbc-4839e3ef067a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c78a1b-af55-4fe7-9769-6471c664d6c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fcff47d-f809-4b67-9198-0428e717b5a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Login/Negative/TC3_Negative_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c78a1b-af55-4fe7-9769-6471c664d6c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f33d614-2f4e-4adc-9bbc-4839e3ef067a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b35207d9-ab92-44c0-9144-26b2bcdeac21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Login/Negative/TC4_Negative_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f33d614-2f4e-4adc-9bbc-4839e3ef067a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c78a1b-af55-4fe7-9769-6471c664d6c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f12c3f09-8300-4d70-83c2-7f0f6dcf8208</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Login/Negative/TC5_Negative_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f33d614-2f4e-4adc-9bbc-4839e3ef067a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c78a1b-af55-4fe7-9769-6471c664d6c5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8b64c710-f181-4e97-acc1-3555fff60f57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC Login/Negative/TC6_Negative_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f33d614-2f4e-4adc-9bbc-4839e3ef067a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c78a1b-af55-4fe7-9769-6471c664d6c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77f40bc9-8ad2-4465-8156-5da0d0615bb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb54675a-8c32-4c6d-bc40-dd738d0e7e70</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
